Linenumber directives from markdown files (#5)
Add line directives (for C and Go codeblocks) in generated file output.

This is useful for debugging as tools such as right-clicking on acme or with gF
are able to go to the correct source line. Typical output with `go run' or `go build':

  # command-line-arguments
  WhitespacePreservation.md:38: invalid character U+0023 '#'
  WhitespacePreservation.md:38: undefined: TEST
  WhitespacePreservation.md:39: missing return at end of function
  LineNumbers.md:147: undefined: parseHeader

If necessary, generated line numbers can be removed with a sed script
such as:

  sed -i '/^\/\/line/d' main.go